<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phone_prefix' => 93,'is_active'=>true),
            array('id' => 2,'code' => 'AL' ,'name' => "Albania",'phone_prefix' => 355,'is_active'=>true),
            array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phone_prefix' => 213,'is_active'=>true),
            array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phone_prefix' => 1684,'is_active'=>true),
            array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'phone_prefix' => 376,'is_active'=>true),
            array('id' => 6,'code' => 'AO' ,'name' => "Angola",'phone_prefix' => 244,'is_active'=>true),
            array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phone_prefix' => 1264,'is_active'=>true),
            array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phone_prefix' => 0,'is_active'=>false),
            array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phone_prefix' => 1268,'is_active'=>true),
            array('id' => 10,'code' => 'AR','name' => "Argentina",'phone_prefix' => 54,'is_active'=>true),
            array('id' => 11,'code' => 'AM','name' => "Armenia",'phone_prefix' => 374,'is_active'=>true),
            array('id' => 12,'code' => 'AW','name' => "Aruba",'phone_prefix' => 297,'is_active'=>true),
            array('id' => 13,'code' => 'AU','name' => "Australia",'phone_prefix' => 61,'is_active'=>true),
            array('id' => 14,'code' => 'AT','name' => "Austria",'phone_prefix' => 43,'is_active'=>true),
            array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phone_prefix' => 994,'is_active'=>true),
            array('id' => 16,'code' => 'BS','name' => "Bahamas The",'phone_prefix' => 1242,'is_active'=>true),
            array('id' => 17,'code' => 'BH','name' => "Bahrain",'phone_prefix' => 973,'is_active'=>true),
            array('id' => 18,'code' => 'BD','name' => "Bangladesh",'phone_prefix' => 880,'is_active'=>true),
            array('id' => 19,'code' => 'BB','name' => "Barbados",'phone_prefix' => 1246,'is_active'=>true),
            array('id' => 20,'code' => 'BY','name' => "Belarus",'phone_prefix' => 375,'is_active'=>true),
            array('id' => 21,'code' => 'BE','name' => "Belgium",'phone_prefix' => 32,'is_active'=>true),
            array('id' => 22,'code' => 'BZ','name' => "Belize",'phone_prefix' => 501,'is_active'=>true),
            array('id' => 23,'code' => 'BJ','name' => "Benin",'phone_prefix' => 229,'is_active'=>true),
            array('id' => 24,'code' => 'BM','name' => "Bermuda",'phone_prefix' => 1441,'is_active'=>true),
            array('id' => 25,'code' => 'BT','name' => "Bhutan",'phone_prefix' => 975,'is_active'=>true),
            array('id' => 26,'code' => 'BO','name' => "Bolivia",'phone_prefix' => 591,'is_active'=>true),
            array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phone_prefix' => 387,'is_active'=>true),
            array('id' => 28,'code' => 'BW','name' => "Botswana",'phone_prefix' => 267,'is_active'=>true),
            array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'phone_prefix' => 0,'is_active'=>true),
            array('id' => 30,'code' => 'BR','name' => "Brazil",'phone_prefix' => 55,'is_active'=>true),
            array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phone_prefix' => 246,'is_active'=>true),
            array('id' => 32,'code' => 'BN','name' => "Brunei",'phone_prefix' => 673,'is_active'=>true),
            array('id' => 33,'code' => 'BG','name' => "Bulgaria",'phone_prefix' => 359,'is_active'=>true),
            array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'phone_prefix' => 226,'is_active'=>true),
            array('id' => 35,'code' => 'BI','name' => "Burundi",'phone_prefix' => 257,'is_active'=>true),
            array('id' => 36,'code' => 'KH','name' => "Cambodia",'phone_prefix' => 855,'is_active'=>true),
            array('id' => 37,'code' => 'CM','name' => "Cameroon",'phone_prefix' => 237,'is_active'=>true),
            array('id' => 38,'code' => 'CA','name' => "Canada",'phone_prefix' => 1,'is_active'=>true),
            array('id' => 39,'code' => 'CV','name' => "Cape Verde",'phone_prefix' => 238,'is_active'=>true),
            array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'phone_prefix' => 1345,'is_active'=>true),
            array('id' => 41,'code' => 'CF','name' => "Central African Republic",'phone_prefix' => 236,'is_active'=>true),
            array('id' => 42,'code' => 'TD','name' => "Chad",'phone_prefix' => 235,'is_active'=>true),
            array('id' => 43,'code' => 'CL','name' => "Chile",'phone_prefix' => 56,'is_active'=>true),
            array('id' => 44,'code' => 'CN','name' => "China",'phone_prefix' => 86,'is_active'=>true),
            array('id' => 45,'code' => 'CX','name' => "Christmas Island",'phone_prefix' => 61,'is_active'=>true),
            array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phone_prefix' => 672,'is_active'=>true),
            array('id' => 47,'code' => 'CO','name' => "Colombia",'phone_prefix' => 57,'is_active'=>true),
            array('id' => 48,'code' => 'KM','name' => "Comoros",'phone_prefix' => 269,'is_active'=>true),
            array('id' => 49,'code' => 'CG','name' => "Congo",'phone_prefix' => 242,'is_active'=>true),
            array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phone_prefix' => 242,'is_active'=>true),
            array('id' => 51,'code' => 'CK','name' => "Cook Islands",'phone_prefix' => 682,'is_active'=>true),
            array('id' => 52,'code' => 'CR','name' => "Costa Rica",'phone_prefix' => 506,'is_active'=>true),
            array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phone_prefix' => 225,'is_active'=>true),
            array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phone_prefix' => 385,'is_active'=>true),
            array('id' => 55,'code' => 'CU','name' => "Cuba",'phone_prefix' => 53,'is_active'=>true),
            array('id' => 56,'code' => 'CY','name' => "Cyprus",'phone_prefix' => 357,'is_active'=>true),
            array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'phone_prefix' => 420,'is_active'=>true),
            array('id' => 58,'code' => 'DK','name' => "Denmark",'phone_prefix' => 45,'is_active'=>true),
            array('id' => 59,'code' => 'DJ','name' => "Djibouti",'phone_prefix' => 253,'is_active'=>true),
            array('id' => 60,'code' => 'DM','name' => "Dominica",'phone_prefix' => 1767,'is_active'=>true),
            array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'phone_prefix' => 1809,'is_active'=>true),
            array('id' => 62,'code' => 'TP','name' => "East Timor",'phone_prefix' => 670,'is_active'=>true),
            array('id' => 63,'code' => 'EC','name' => "Ecuador",'phone_prefix' => 593,'is_active'=>true),
            array('id' => 64,'code' => 'EG','name' => "Egypt",'phone_prefix' => 20,'is_active'=>true),
            array('id' => 65,'code' => 'SV','name' => "El Salvador",'phone_prefix' => 503,'is_active'=>true),
            array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phone_prefix' => 240,'is_active'=>true),
            array('id' => 67,'code' => 'ER','name' => "Eritrea",'phone_prefix' => 291,'is_active'=>true),
            array('id' => 68,'code' => 'EE','name' => "Estonia",'phone_prefix' => 372,'is_active'=>true),
            array('id' => 69,'code' => 'ET','name' => "Ethiopia",'phone_prefix' => 251,'is_active'=>true),
            array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phone_prefix' => 61,'is_active'=>true),
            array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'phone_prefix' => 500,'is_active'=>true),
            array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'phone_prefix' => 298,'is_active'=>true),
            array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phone_prefix' => 679,'is_active'=>true),
            array('id' => 74,'code' => 'FI','name' => "Finland",'phone_prefix' => 358,'is_active'=>true),
            array('id' => 75,'code' => 'FR','name' => "France",'phone_prefix' => 33,'is_active'=>true),
            array('id' => 76,'code' => 'GF','name' => "French Guiana",'phone_prefix' => 594,'is_active'=>true),
            array('id' => 77,'code' => 'PF','name' => "French Polynesia",'phone_prefix' => 689,'is_active'=>true),
            array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'phone_prefix' => 0,'is_active'=>true),
            array('id' => 79,'code' => 'GA','name' => "Gabon",'phone_prefix' => 241,'is_active'=>true),
            array('id' => 80,'code' => 'GM','name' => "Gambia The",'phone_prefix' => 220,'is_active'=>true),
            array('id' => 81,'code' => 'GE','name' => "Georgia",'phone_prefix' => 995,'is_active'=>true),
            array('id' => 82,'code' => 'DE','name' => "Germany",'phone_prefix' => 49,'is_active'=>true),
            array('id' => 83,'code' => 'GH','name' => "Ghana",'phone_prefix' => 233,'is_active'=>true),
            array('id' => 84,'code' => 'GI','name' => "Gibraltar",'phone_prefix' => 350,'is_active'=>true),
            array('id' => 85,'code' => 'GR','name' => "Greece",'phone_prefix' => 30,'is_active'=>true),
            array('id' => 86,'code' => 'GL','name' => "Greenland",'phone_prefix' => 299,'is_active'=>true),
            array('id' => 87,'code' => 'GD','name' => "Grenada",'phone_prefix' => 1473,'is_active'=>true),
            array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'phone_prefix' => 590,'is_active'=>true),
            array('id' => 89,'code' => 'GU','name' => "Guam",'phone_prefix' => 1671,'is_active'=>true),
            array('id' => 90,'code' => 'GT','name' => "Guatemala",'phone_prefix' => 502,'is_active'=>true),
            array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phone_prefix' => 44,'is_active'=>true),
            array('id' => 92,'code' => 'GN','name' => "Guinea",'phone_prefix' => 224,'is_active'=>true),
            array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phone_prefix' => 245,'is_active'=>true),
            array('id' => 94,'code' => 'GY','name' => "Guyana",'phone_prefix' => 592,'is_active'=>true),
            array('id' => 95,'code' => 'HT','name' => "Haiti",'phone_prefix' => 509,'is_active'=>true),
            array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phone_prefix' => 0,'is_active'=>true),
            array('id' => 97,'code' => 'HN','name' => "Honduras",'phone_prefix' => 504,'is_active'=>true),
            array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phone_prefix' => 852,'is_active'=>true),
            array('id' => 99,'code' => 'HU','name' => "Hungary",'phone_prefix' => 36,'is_active'=>true),
            array('id' => 100,'code' => 'IS','name' => "Iceland",'phone_prefix' => 354,'is_active'=>true),
            array('id' => 101,'code' => 'IN','name' => "India",'phone_prefix' => 91,'is_active'=>true),
            array('id' => 102,'code' => 'ID','name' => "Indonesia",'phone_prefix' => 62,'is_active'=>true),
            array('id' => 103,'code' => 'IR','name' => "Iran",'phone_prefix' => 98,'is_active'=>true),
            array('id' => 104,'code' => 'IQ','name' => "Iraq",'phone_prefix' => 964,'is_active'=>true),
            array('id' => 105,'code' => 'IE','name' => "Ireland",'phone_prefix' => 353,'is_active'=>true),
            array('id' => 106,'code' => 'IL','name' => "Israel",'phone_prefix' => 972,'is_active'=>true),
            array('id' => 107,'code' => 'IT','name' => "Italy",'phone_prefix' => 39,'is_active'=>true),
            array('id' => 108,'code' => 'JM','name' => "Jamaica",'phone_prefix' => 1876,'is_active'=>true),
            array('id' => 109,'code' => 'JP','name' => "Japan",'phone_prefix' => 81,'is_active'=>true),
            array('id' => 110,'code' => 'XJ','name' => "Jersey",'phone_prefix' => 44,'is_active'=>true),
            array('id' => 111,'code' => 'JO','name' => "Jordan",'phone_prefix' => 962,'is_active'=>true),
            array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phone_prefix' => 7,'is_active'=>true),
            array('id' => 113,'code' => 'KE','name' => "Kenya",'phone_prefix' => 254,'is_active'=>true),
            array('id' => 114,'code' => 'KI','name' => "Kiribati",'phone_prefix' => 686,'is_active'=>true),
            array('id' => 115,'code' => 'KP','name' => "Korea North",'phone_prefix' => 850,'is_active'=>true),
            array('id' => 116,'code' => 'KR','name' => "Korea South",'phone_prefix' => 82,'is_active'=>true),
            array('id' => 117,'code' => 'KW','name' => "Kuwait",'phone_prefix' => 965,'is_active'=>true),
            array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phone_prefix' => 996,'is_active'=>true),
            array('id' => 119,'code' => 'LA','name' => "Laos",'phone_prefix' => 856,'is_active'=>true),
            array('id' => 120,'code' => 'LV','name' => "Latvia",'phone_prefix' => 371,'is_active'=>true),
            array('id' => 121,'code' => 'LB','name' => "Lebanon",'phone_prefix' => 961,'is_active'=>true),
            array('id' => 122,'code' => 'LS','name' => "Lesotho",'phone_prefix' => 266,'is_active'=>true),
            array('id' => 123,'code' => 'LR','name' => "Liberia",'phone_prefix' => 231,'is_active'=>true),
            array('id' => 124,'code' => 'LY','name' => "Libya",'phone_prefix' => 218,'is_active'=>true),
            array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'phone_prefix' => 423,'is_active'=>true),
            array('id' => 126,'code' => 'LT','name' => "Lithuania",'phone_prefix' => 370,'is_active'=>true),
            array('id' => 127,'code' => 'LU','name' => "Luxembourg",'phone_prefix' => 352,'is_active'=>true),
            array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phone_prefix' => 853,'is_active'=>true),
            array('id' => 129,'code' => 'MK','name' => "Macedonia",'phone_prefix' => 389,'is_active'=>true),
            array('id' => 130,'code' => 'MG','name' => "Madagascar",'phone_prefix' => 261,'is_active'=>true),
            array('id' => 131,'code' => 'MW','name' => "Malawi",'phone_prefix' => 265,'is_active'=>true),
            array('id' => 132,'code' => 'MY','name' => "Malaysia",'phone_prefix' => 60,'is_active'=>true),
            array('id' => 133,'code' => 'MV','name' => "Maldives",'phone_prefix' => 960,'is_active'=>true),
            array('id' => 134,'code' => 'ML','name' => "Mali",'phone_prefix' => 223,'is_active'=>true),
            array('id' => 135,'code' => 'MT','name' => "Malta",'phone_prefix' => 356,'is_active'=>true),
            array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phone_prefix' => 44,'is_active'=>true),
            array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'phone_prefix' => 692,'is_active'=>true),
            array('id' => 138,'code' => 'MQ','name' => "Martinique",'phone_prefix' => 596,'is_active'=>true),
            array('id' => 139,'code' => 'MR','name' => "Mauritania",'phone_prefix' => 222,'is_active'=>true),
            array('id' => 140,'code' => 'MU','name' => "Mauritius",'phone_prefix' => 230,'is_active'=>true),
            array('id' => 141,'code' => 'YT','name' => "Mayotte",'phone_prefix' => 269,'is_active'=>true),
            array('id' => 142,'code' => 'MX','name' => "Mexico",'phone_prefix' => 52,'is_active'=>true),
            array('id' => 143,'code' => 'FM','name' => "Micronesia",'phone_prefix' => 691,'is_active'=>true),
            array('id' => 144,'code' => 'MD','name' => "Moldova",'phone_prefix' => 373,'is_active'=>true),
            array('id' => 145,'code' => 'MC','name' => "Monaco",'phone_prefix' => 377,'is_active'=>true),
            array('id' => 146,'code' => 'MN','name' => "Mongolia",'phone_prefix' => 976,'is_active'=>true),
            array('id' => 147,'code' => 'MS','name' => "Montserrat",'phone_prefix' => 1664,'is_active'=>true),
            array('id' => 148,'code' => 'MA','name' => "Morocco",'phone_prefix' => 212,'is_active'=>true),
            array('id' => 149,'code' => 'MZ','name' => "Mozambique",'phone_prefix' => 258,'is_active'=>true),
            array('id' => 150,'code' => 'MM','name' => "Myanmar",'phone_prefix' => 95,'is_active'=>true),
            array('id' => 151,'code' => 'NA','name' => "Namibia",'phone_prefix' => 264,'is_active'=>true),
            array('id' => 152,'code' => 'NR','name' => "Nauru",'phone_prefix' => 674,'is_active'=>true),
            array('id' => 153,'code' => 'NP','name' => "Nepal",'phone_prefix' => 977,'is_active'=>true),
            array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phone_prefix' => 599,'is_active'=>true),
            array('id' => 155,'code' => 'NL','name' => "Netherlands The",'phone_prefix' => 31,'is_active'=>true),
            array('id' => 156,'code' => 'NC','name' => "New Caledonia",'phone_prefix' => 687,'is_active'=>true),
            array('id' => 157,'code' => 'NZ','name' => "New Zealand",'phone_prefix' => 64,'is_active'=>true),
            array('id' => 158,'code' => 'NI','name' => "Nicaragua",'phone_prefix' => 505,'is_active'=>true),
            array('id' => 159,'code' => 'NE','name' => "Niger",'phone_prefix' => 227,'is_active'=>true),
            array('id' => 160,'code' => 'NG','name' => "Nigeria",'phone_prefix' => 234,'is_active'=>true),
            array('id' => 161,'code' => 'NU','name' => "Niue",'phone_prefix' => 683,'is_active'=>true),
            array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'phone_prefix' => 672,'is_active'=>true),
            array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phone_prefix' => 1670,'is_active'=>true),
            array('id' => 164,'code' => 'NO','name' => "Norway",'phone_prefix' => 47,'is_active'=>true),
            array('id' => 165,'code' => 'OM','name' => "Oman",'phone_prefix' => 968,'is_active'=>true),
            array('id' => 166,'code' => 'PK','name' => "Pakistan",'phone_prefix' => 92,'is_active'=>true),
            array('id' => 167,'code' => 'PW','name' => "Palau",'phone_prefix' => 680,'is_active'=>true),
            array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phone_prefix' => 970,'is_active'=>true),
            array('id' => 169,'code' => 'PA','name' => "Panama",'phone_prefix' => 507,'is_active'=>true),
            array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phone_prefix' => 675,'is_active'=>true),
            array('id' => 171,'code' => 'PY','name' => "Paraguay",'phone_prefix' => 595,'is_active'=>true),
            array('id' => 172,'code' => 'PE','name' => "Peru",'phone_prefix' => 51,'is_active'=>true),
            array('id' => 173,'code' => 'PH','name' => "Philippines",'phone_prefix' => 63,'is_active'=>true),
            array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phone_prefix' => 0,'is_active'=>true),
            array('id' => 175,'code' => 'PL','name' => "Poland",'phone_prefix' => 48,'is_active'=>true),
            array('id' => 176,'code' => 'PT','name' => "Portugal",'phone_prefix' => 351,'is_active'=>true),
            array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'phone_prefix' => 1787,'is_active'=>true),
            array('id' => 178,'code' => 'QA','name' => "Qatar",'phone_prefix' => 974,'is_active'=>true),
            array('id' => 179,'code' => 'RE','name' => "Reunion",'phone_prefix' => 262,'is_active'=>true),
            array('id' => 180,'code' => 'RO','name' => "Romania",'phone_prefix' => 40,'is_active'=>true),
            array('id' => 181,'code' => 'RU','name' => "Russia",'phone_prefix' => 70,'is_active'=>true),
            array('id' => 182,'code' => 'RW','name' => "Rwanda",'phone_prefix' => 250,'is_active'=>true),
            array('id' => 183,'code' => 'SH','name' => "Saint Helena",'phone_prefix' => 290,'is_active'=>true),
            array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phone_prefix' => 1869,'is_active'=>true),
            array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'phone_prefix' => 1758,'is_active'=>true),
            array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phone_prefix' => 508,'is_active'=>true),
            array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phone_prefix' => 1784,'is_active'=>true),
            array('id' => 188,'code' => 'WS','name' => "Samoa",'phone_prefix' => 684,'is_active'=>true),
            array('id' => 189,'code' => 'SM','name' => "San Marino",'phone_prefix' => 378,'is_active'=>true),
            array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phone_prefix' => 239,'is_active'=>true),
            array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phone_prefix' => 966,'is_active'=>true),
            array('id' => 192,'code' => 'SN','name' => "Senegal",'phone_prefix' => 221,'is_active'=>true),
            array('id' => 193,'code' => 'RS','name' => "Serbia",'phone_prefix' => 381,'is_active'=>true),
            array('id' => 194,'code' => 'SC','name' => "Seychelles",'phone_prefix' => 248,'is_active'=>true),
            array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'phone_prefix' => 232,'is_active'=>true),
            array('id' => 196,'code' => 'SG','name' => "Singapore",'phone_prefix' => 65,'is_active'=>true),
            array('id' => 197,'code' => 'SK','name' => "Slovakia",'phone_prefix' => 421,'is_active'=>true),
            array('id' => 198,'code' => 'SI','name' => "Slovenia",'phone_prefix' => 386,'is_active'=>true),
            array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phone_prefix' => 44,'is_active'=>true),
            array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'phone_prefix' => 677,'is_active'=>true),
            array('id' => 201,'code' => 'SO','name' => "Somalia",'phone_prefix' => 252,'is_active'=>true),
            array('id' => 202,'code' => 'ZA','name' => "South Africa",'phone_prefix' => 27,'is_active'=>true),
            array('id' => 203,'code' => 'GS','name' => "South Georgia",'phone_prefix' => 0,'is_active'=>true),
            array('id' => 204,'code' => 'SS','name' => "South Sudan",'phone_prefix' => 211,'is_active'=>true),
            array('id' => 205,'code' => 'ES','name' => "Spain",'phone_prefix' => 34,'is_active'=>true),
            array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'phone_prefix' => 94,'is_active'=>true),
            array('id' => 207,'code' => 'SD','name' => "Sudan",'phone_prefix' => 249,'is_active'=>true),
            array('id' => 208,'code' => 'SR','name' => "Suriname",'phone_prefix' => 597,'is_active'=>true),
            array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phone_prefix' => 47,'is_active'=>true),
            array('id' => 210,'code' => 'SZ','name' => "Swaziland",'phone_prefix' => 268,'is_active'=>true),
            array('id' => 211,'code' => 'SE','name' => "Sweden",'phone_prefix' => 46,'is_active'=>true),
            array('id' => 212,'code' => 'CH','name' => "Switzerland",'phone_prefix' => 41,'is_active'=>true),
            array('id' => 213,'code' => 'SY','name' => "Syria",'phone_prefix' => 963,'is_active'=>true),
            array('id' => 214,'code' => 'TW','name' => "Taiwan",'phone_prefix' => 886,'is_active'=>true),
            array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'phone_prefix' => 992,'is_active'=>true),
            array('id' => 216,'code' => 'TZ','name' => "Tanzania",'phone_prefix' => 255,'is_active'=>true),
            array('id' => 217,'code' => 'TH','name' => "Thailand",'phone_prefix' => 66,'is_active'=>true),
            array('id' => 218,'code' => 'TG','name' => "Togo",'phone_prefix' => 228,'is_active'=>true),
            array('id' => 219,'code' => 'TK','name' => "Tokelau",'phone_prefix' => 690,'is_active'=>true),
            array('id' => 220,'code' => 'TO','name' => "Tonga",'phone_prefix' => 676,'is_active'=>true),
            array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phone_prefix' => 1868,'is_active'=>true),
            array('id' => 222,'code' => 'TN','name' => "Tunisia",'phone_prefix' => 216,'is_active'=>true),
            array('id' => 223,'code' => 'TR','name' => "Turkey",'phone_prefix' => 90,'is_active'=>true),
            array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'phone_prefix' => 7370,'is_active'=>true),
            array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phone_prefix' => 1649,'is_active'=>true),
            array('id' => 226,'code' => 'TV','name' => "Tuvalu",'phone_prefix' => 688,'is_active'=>true),
            array('id' => 227,'code' => 'UG','name' => "Uganda",'phone_prefix' => 256,'is_active'=>true),
            array('id' => 228,'code' => 'UA','name' => "Ukraine",'phone_prefix' => 380,'is_active'=>true),
            array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phone_prefix' => 971,'is_active'=>true),
            array('id' => 230,'code' => 'GB','name' => "United Kingdom",'phone_prefix' => 44,'is_active'=>true),
            array('id' => 231,'code' => 'US','name' => "United States",'phone_prefix' => 1,'is_active'=>true),
            array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phone_prefix' => 1,'is_active'=>true),
            array('id' => 233,'code' => 'UY','name' => "Uruguay",'phone_prefix' => 598,'is_active'=>true),
            array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phone_prefix' => 998,'is_active'=>true),
            array('id' => 235,'code' => 'VU','name' => "Vanuatu",'phone_prefix' => 678,'is_active'=>true),
            array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phone_prefix' => 39,'is_active'=>true),
            array('id' => 237,'code' => 'VE','name' => "Venezuela",'phone_prefix' => 58,'is_active'=>true),
            array('id' => 238,'code' => 'VN','name' => "Vietnam",'phone_prefix' => 84,'is_active'=>true),
            array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phone_prefix' => 1284,'is_active'=>true),
            array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phone_prefix' => 1340,'is_active'=>true),
            array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phone_prefix' => 681,'is_active'=>true),
            array('id' => 242,'code' => 'EH','name' => "Western Sahara",'phone_prefix' => 212,'is_active'=>true),
            array('id' => 243,'code' => 'YE','name' => "Yemen",'phone_prefix' => 967,'is_active'=>true),
            array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'phone_prefix' => 38,'is_active'=>true),
            array('id' => 245,'code' => 'ZM','name' => "Zambia",'phone_prefix' => 260,'is_active'=>true),
            array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phone_prefix' => 263,'is_active'=>true),
        );
        DB::table('countries')->insert($countries);
    }
}
