<?php

namespace Database\Seeders;

use App\Models\BankDetail;
use App\Models\SellCertificate;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubscriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user           =   User::role('user')->whereHas('creditCard')->inRandomOrder()->first();
        $certificate    =   SellCertificate::whereHas('certificate.user.creditCard')->inRandomOrder()->first();
        $user_id        =   $certificate->user_id;
        $certificate_id =   $certificate->id;
        $subsc = array(
            array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=> BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => $user->name,
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1500,
                'amount'=>1500,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-09-15 10:05:04',
                'updated_at'=> '2022-09-15 10:05:04'
            ),
            array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1700,
                'amount'=>1700,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2022-09-25 10:05:04',
                'updated_at'=> '2022-09-25 10:05:04'
            ),
            array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1200,
                'amount'=>1200,
                'quantity'=>14,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-10-05 10:05:04',
                'updated_at'=> '2022-10-05 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2500,
                'amount'=>2500,
                'quantity'=>27,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-10-22 10:05:04',
                'updated_at'=> '2022-10-22 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>4500,
                'amount'=>4500,
                'quantity'=>47,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2022-11-07 10:05:04',
                'updated_at'=> '2022-11-07 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2200,
                'amount'=>2200,
                'quantity'=>22,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-11-28 10:05:04',
                'updated_at'=> '2022-11-28 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2700,
                'amount'=>2700,
                'quantity'=>25,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2022-12-03 10:05:04',
                'updated_at'=> '2022-12-03 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1950,
                'amount'=>1950,
                'quantity'=>18,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-12-09 10:05:04',
                'updated_at'=> '2022-12-09 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>900,
                'amount'=>900,
                'quantity'=>10,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-12-13 10:05:04',
                'updated_at'=> '2022-12-13 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1500,
                'amount'=>1500,
                'quantity'=>13,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2022-12-18 10:05:04',
                'updated_at'=> '2022-12-18 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2780,
                'amount'=>2780,
                'quantity'=>28,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-12-25 10:05:04',
                'updated_at'=> '2022-12-25 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2350,
                'amount'=>2350,
                'quantity'=>24,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2022-12-30 10:05:04',
                'updated_at'=> '2022-12-30 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3260,
                'amount'=>3260,
                'quantity'=>34,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-01-01 10:05:04',
                'updated_at'=> '2023-01-01 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3800,
                'amount'=>3800,
                'quantity'=>35,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-03 10:05:04',
                'updated_at'=> '2023-01-03 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1700,
                'amount'=>1700,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-06 10:05:04',
                'updated_at'=> '2023-01-06 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3950,
                'amount'=>3950,
                'quantity'=>40,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-01-09 10:05:04',
                'updated_at'=> '2023-01-09 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1900,
                'amount'=>1900,
                'quantity'=>18,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-11 10:05:04',
                'updated_at'=> '2023-01-11 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3120,
                'amount'=>3120,
                'quantity'=>34,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-13 10:05:04',
                'updated_at'=> '2023-01-13 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3180,
                'amount'=>3180,
                'quantity'=>34,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-01-15 10:05:04',
                'updated_at'=> '2023-01-15 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1650,
                'amount'=>1650,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-19 10:05:04',
                'updated_at'=> '2023-01-19 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3600,
                'amount'=>3600,
                'quantity'=>35,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-20 10:05:04',
                'updated_at'=> '2023-01-20 10:05:04'
            ),


            array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3120,
                'amount'=>3120,
                'quantity'=>30,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-26 10:05:04',
                'updated_at'=> '2023-01-26 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3180,
                'amount'=>3180,
                'quantity'=>30,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-01-27 10:05:04',
                'updated_at'=> '2023-01-27 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1650,
                'amount'=>1650,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-29 10:05:04',
                'updated_at'=> '2023-01-29 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>250,
                'amount'=>250,
                'quantity'=>3,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-30 10:05:04',
                'updated_at'=> '2023-01-30 10:05:04'
            ),
            array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>5200,
                'amount'=>5200,
                'quantity'=>50,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-01-31 10:05:04',
                'updated_at'=> '2023-01-31 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2950,
                'amount'=>2950,
                'quantity'=>30,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-01 10:05:04',
                'updated_at'=> '2023-02-01 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1650,
                'amount'=>1650,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-02 10:05:04',
                'updated_at'=> '2023-02-02 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2400,
                'amount'=>2400,
                'quantity'=>22,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-03 10:05:04',
                'updated_at'=> '2023-02-03 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3560,
                'amount'=>3560,
                'quantity'=>38,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-04 10:05:04',
                'updated_at'=> '2023-02-04 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2658,
                'amount'=>2658,
                'quantity'=>25,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-05 10:05:04',
                'updated_at'=> '2023-02-05 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1490,
                'amount'=>1490,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-05 10:05:04',
                'updated_at'=> '2023-02-05 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2800,
                'amount'=>2800,
                'quantity'=>26,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-05 10:05:04',
                'updated_at'=> '2023-02-05 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3150,
                'amount'=>3150,
                'quantity'=>33,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-05 10:05:04',
                'updated_at'=> '2023-02-05 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3800,
                'amount'=>3800,
                'quantity'=>36,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-06 10:05:04',
                'updated_at'=> '2023-02-06 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1950,
                'amount'=>1950,
                'quantity'=>16,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-06 10:05:04',
                'updated_at'=> '2023-02-06 10:05:04'
            ),array(
                'user_id' => 193,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1900,
                'amount'=>1900,
                'quantity'=>16,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-06 10:05:04',
                'updated_at'=> '2023-02-06 10:05:04'
            ),array(
                'user_id' => 193,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>5800,
                'amount'=>5800,
                'quantity'=>60,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-07 10:05:04',
                'updated_at'=> '2023-02-07 10:05:04'
            ),array(
                'user_id' => 193,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>9900,
                'amount'=>9900,
                'quantity'=>86,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-08 10:05:04',
                'updated_at'=> '2023-02-08 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1650,
                'amount'=>1650,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-08 10:05:04',
                'updated_at'=> '2023-02-08 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3580,
                'amount'=>3580,
                'quantity'=>34,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-09 10:05:04',
                'updated_at'=> '2023-02-09 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2150,
                'amount'=>2150,
                'quantity'=>20,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-10 10:05:04',
                'updated_at'=> '2023-02-10 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3180,
                'amount'=>3180,
                'quantity'=>30,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-11 10:05:04',
                'updated_at'=> '2023-02-11 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1750,
                'amount'=>1750,
                'quantity'=>16,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-11 10:05:04',
                'updated_at'=> '2023-02-11 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>6000,
                'amount'=>6000,
                'quantity'=>62,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-11 10:05:04',
                'updated_at'=> '2023-02-11 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>5500,
                'amount'=>5500,
                'quantity'=>58,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-12 10:05:04',
                'updated_at'=> '2023-02-12 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>4200,
                'amount'=>4200,
                'quantity'=>40,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>1,
                'created_at'=> '2023-02-12 10:05:04',
                'updated_at'=> '2023-02-12 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>1450,
                'amount'=>1450,
                'quantity'=>16,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-13 10:05:04',
                'updated_at'=> '2023-02-13 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2350,
                'amount'=>2350,
                'quantity'=>21,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-13 10:05:04',
                'updated_at'=> '2023-02-13 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>2850,
                'amount'=>2850,
                'quantity'=>15,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-14 10:05:04',
                'updated_at'=> '2023-02-14 10:05:04'
            ),array(
                'user_id' => $user->id,
                'receiver_id' => $user_id,//seller
                'seller_bank_id'=>BankDetail::where('user_id',$user_id)->inRandomOrder()->first()->id,
                'ip_address'=>'192.168.2.24',
                'name' => "Ashish Panchal",
                'stripe_id' => rand(0,999999999),
                'stripe_status'=>'success',
                'stripe_price'=>3600,
                'amount'=>3600,
                'quantity'=>31,
                'trial_ends_at'=>null,
                'ends_at'=>null,
                'certificate_id'=>$certificate_id,
                'card_detail_id'=>$user->creditCard->id,
                'created_at'=> '2023-02-14 10:05:04',
                'updated_at'=> '2023-02-14 10:05:04'
            ),
        );
        DB::table('subscriptions')->insert($subsc);
    }
}
